### ISSUE TITLE
Hide, ignore, collapse or zoom

### ISSUE THREAD

**Issue by crumeniferus** [jklingen/space-inspector#6]
The box view is a great concept that I find much easier to use in many cases than a list view. The main drawback for me in its present form is scaling of the smaller files and folders. If it were possible to hide, ignore or collapse a very large file/folder, there would be more screen available to show the information of some of the small items.

I would favour collapsing over the rest and a small box at the top bearing the legend “<n> files collapsed. Total <size>”. A tap on the box could reveal a list of collapsed files and their sizes and selecting one would un-collapse it. An option to “Uncollapse all” would be useful here too. To collapse an item, I think a long press on the box should open the option list.

**Comment by crumeniferus** [comment]
I forgot that angle brackets would be interpreted as an attempt at markup. The legend mentioned above should have read as “(n) files collapsed. Total (size)”.

**Comment by jklingen** [comment]
Hey, thanks for your ideas. Actually I have added the list view for the purpose of inspecting smaller folders, but you are right: it would be great to have the visual comparison, too. I'd go for the collapse option, sounds best from usability point of view :)

**Comment by crumeniferus** [comment]
Cool. Thanks for listening.

On Sun, 20 Apr 2014 22:23:57 -0700
jklingen notifications@github.com wrote:

> Hey, thanks for your ideas. Actually I have added the list view for
> the purpose of inspecting smaller folders, but you are right: it
> would be great to have the visual comparison, too. I'd go for the
> collapse option, sounds best from usability point of view :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jklingen/space-inspector/issues/6#issuecomment-40917002

## 

Ian Cheesbrough
Sound Engineer
Lighting Designer
Programmer

**Comment by jklingen** [comment]
I just gave this some more thoughts and had another idea... Am I right to assume that the motivation for this request is solely that you would like to be able to see and access smaller files and folders quickly? Or is there another aspect I am missing?

While collapsing would be great in most cases (when one or two subdirectories make up most of a directory's size), it could also get tedious in some cases, e.g. with 10 large subdirectories of roughly the same size and a single smaller subdirectory, the user would then need to repeatedly compress the larger subdirectories until he gets to actually see the small subdirectory. Compressing would probably have to be done via the contextmenu which would make the task even more tedious.

So the idea is to group smaller subdirectories/files together (the ones which make less than ~5% of the directory size and thus cannot be tapped on properly) until they exceed ~5%, and upon tapping it, opening only these  grouped subdirectories/files in a new window. 

Pro: even very small files would just be a single tap away.
Contra: opening a partial directory in a new window is a breach in the navigation concept, but it should be possible to visually differentiate this view.

What do you think? Would this solution work for you?

**Comment by crumeniferus** [comment]
Hi.

Sorry about the delay, I've been away for a while.

On Mon, 12 May 2014 14:34:47 -0700
jklingen notifications@github.com wrote:

> I just gave this some more thoughts and had another idea... Am I
> right to assume that the motivation for this request is solely that
> you would like to be able to see and access smaller files and folders
> quickly? Or is there another aspect I am missing?

That's pretty much it. When the small files are a lot smaller than other
files, it can be hard to see them. You missed nothing :-)

> While collapsing would be great in most cases (when one or two
> subdirectories make up most of a directory's size), it could also get
> tedious in some cases, e.g. with 10 large subdirectories of roughly
> the same size and a single smaller subdirectory, the user would then
> need to repeatedly compress the larger subdirectories until he gets
> to actually see the small subdirectory. Compressing would probably
> have to be done via the contextmenu which would make the task even
> more tedious.

Fair point. The idea of collapsing came to me after looking at some
directories containing one or two sub-folders that accounted for
about half the total size, and a few very small files that were too
small to show the text. As you say, collapsing wouldn't help in the
other scenario you describe, which I hadn't considered.

> So the idea is to group smaller subdirectories/files together (the
> ones which make less than ~5% of the directory size and thus cannot
> be tapped on properly) until they exceed ~5%, and upon tapping it,
> opening only these  grouped subdirectories/files in a new window. 

That's an elegant idea, I think.

> Pro: even very small files would just be a single tap away.
> Contra: opening a partial directory in a new window is a breach in
> the navigation concept, but it should be possible to visually
> differentiate this view.
> 
> What do you think? Would this solution work for you?

I like your idea. It sounds a bit like a zoom function when I think
about it. Maybe that's the key to making it fit into the navigation
concept: double tap on the area that indicates a collection of small
files and you get a "zoomed in" view of that area (this is how the
internet browser zooms in and differentiates from the single tap for
following a link). A pinch together gesture could return you to the
full view, just like the image gallery and the internet browser do. The
zooming need not be a truly visual zoom like the gallery and browser,
but using the same gesture vocabulary should help fit in with the
Sailfish way, and thus help the user understand what's gong on with the
display.

It occurred to me that there could be further, even smaller files that
present the same situation even after the first zoom, so further zooming
might be necessary. In this case, each zoom out gesture (whatever you
decide that to be) should probably go back only one level of zoom,
just to help the user keep a mental picture of where they are.

Does this help, or just make it way more complicated than you intended?

## 

Ian Cheesbrough
Sound Engineer
Lighting Designer
Programmer

**Comment by jklingen** [comment]
Never mind, thanks for your detailed feedback. Nice idea, maybe my way of thinking was outside the box... a zoom feature would probably be easier to understand than what I had in mind... 
From what I've read, it shouldn't be too complicated to implement... however, I will need to have a deeper look into this first.

Thanks so far, I'll keep you updated on this :)

**Comment by crumeniferus** [comment]
Okay no problem. Thank you very much for taking my suggestion seriously.

On Tue, 20 May 2014 14:11:19 -0700
jklingen notifications@github.com wrote:

> Never mind, thanks for your detailed feedback. Nice idea, maybe my
> way of thinking was outside the box... a zoom feature would probably
> be easier to understand than what I had in mind... From what I've
> read, it shouldn't be too complicated to implement... however, I will
> need to have a deeper look into this first.
> 
> Thanks so far, I'll keep you updated on this :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jklingen/space-inspector/issues/6#issuecomment-43683750

## 

Ian Cheesbrough
Sound Engineer
Lighting Designer
Programmer

**Comment by jklingen** [comment]
Hey there - just wanted to let you know about the progress of this. In the meantime, I have been doing some testing with the `Pincharea` element for zooming - it actually is easy to _implement_, but it is terrible to _use_ in combination with `Flickable` (for the pulley menu) and `MouseArea` (for the clickable boxes): it is kind of a lottery which one of them will react to your touch ;-)

Thus, the next version will come with a collapse feature :)

**Comment by crumeniferus** [comment]
Okay cool. Thats great news. Shame about the
Flickable/MouseArea/Pincharea issue (which deserves a name like "The FMP
Uncertainty Principle").
Thanks for keeping me in touch. I look forward to trying it out.

On Mon, 03 Nov 2014 13:33:09 -0800
jklingen notifications@github.com wrote:

> Hey there - just wanted to let you know about the progress of this.
> In the meantime, I have been doing some testing with the `Pincharea`
> element for zooming - it actually is easy to _implement_, but it is
> terrible to _use_ in combination with `Flickable` (for the pulley
> menu) and `MouseArea` (for the clickable boxes): it is kind of a
> lottery which one of them will react to your touch ;-)
> 
> Thus, the next version will come with a collapse feature :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jklingen/space-inspector/issues/6#issuecomment-61552498

## 

Ian Cheesbrough
Sound Engineer
Lighting Designer
Programmer
